EOI EQU 20H
IMR EQU 21H
IRR EQU 22H
ISR EQU 23H
INT0 EQU 24H
INT1 EQU 25H
INT2 EQU 26h


ORG 1000H
MENSAJE DB "VAMOS LAS INTERRUPCIONES!"
FIN DB ?


ORG 3000H
;subrutina para imprimir
IMPRIMIR: MOV BX,OFFSET MENSAJE ;IMPRIMIR
          MOV AL,OFFSET FIN - OFFSET MENSAJE
          INT 7
          
          ;AVISAR AL PIC QUE TERMINE
          MOV AL,EOI
          OUT EOI, AL

          ;VOLVEMOS CON IRETL
          IRET
          
ORG 2000H
;SELECCIONAR ID 10 PARA EL F10(PUEDE SER CUALQUIER ID.)
MOV AX,IMPRIMIR
MOV BX,40
MOV [BX],AX ;USO EL BX PARA GUARDAR EL ID NE LE VECTOR DE INTERRUPCIONES.\

CLI
  MOV AL,11111110B ;NO LE DOY BOLA A NADIE, EXEPTO AL F10!!!!!
  OUT IMR,AL
  MOV AL,10
  OUT INT0,AL
STI
LOOP:JMP LOOP

END
